server:
  port: 8081
spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: EMBEDDED
  h2:
    console:
      enabled: true
#logging:
logging:
  level:
    com:
      falconcamp:
        cloud:
          rms: debug
#    org.hibernate:
#        sql: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#    com.zaxxer.hikari:
#      HikariConfig: DEBUG